As/sc codereview 01
HorizenOfficial/zen pull request #189
Opened 2019-09-24 15:09 UTC by alsala

2019-09-27 16:08 UTC, albertog78 requested changes

2019-09-27 16:08 UTC, albertog78 commented on src/main.cpp
> +		if (tx.nVersion > CTransaction::MAX_OLD_VERSION ||
Introduce fork manager to detect if sidechain related txs are already enabled

2019-09-27 16:08 UTC, albertog78 commented on src/main.cpp
> +    if (!scMgr.checkSidechainCreationFunds(tx, nHeight) )
First verify with fork manager if sidechain related txs are already enabled and check tx.nVersion.

In SidechainManager create a general method for SC contextualChecktransaction to perform all the checks needed

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +class CTxForwardTransferCrosschainOut : public CTxCrosschainOut
CTxForwardTransferOut

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +class CTxScCreationCrosschainOut
CTxScCreationOut

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +class CTxCertifierLockCrosschainOut : public CTxCrosschainOut
CTxCertifierLockOut

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +    bool ccIsNull() const {
hasCrosschainOutputs

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::checkMemPool(CTxMemPool& pool, const CTransaction& tx, CValidationState& state)
IsTxAllowedInMempool, make pool const

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::checkCreationInMemPool(CTxMemPool& pool, const CTransaction& tx)
hasSCCreationConflictsInMempool

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +                if (mpTx.nVersion == SC_TX_VERSION)
vsc_ccout is empty in case mpTx.nVersion != SC_TX_VERSION,
remove "if"

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +    if (tx.nVersion == SC_TX_VERSION && tx.vsc_ccout.size() )
"if" is not needed because we already enforce if cross chain outputs are allowed in checktransaction

2019-09-27 16:08 UTC, albertog78 commented on src/main.cpp
> +		if(tx.nVersion < TRANSPARENT_TX_VERSION && tx.nVersion != SC_TX_VERSION) {
if groth is still not active, SC related txs are not active too. remove "&& tx.nVersion != SC_TX_VERSION"

2019-09-27 16:08 UTC, albertog78 commented on src/main.cpp
> +    if (!scMgr.onBlockConnected(*pblock, pindexNew->nHeight) )
Block connect and disconnect to perform efficient updates on balance in case of blocks reverted, should keep track of undo operations. In particular we should use the CBlockUndo and CTXUndo structures to associate the information needed to be able to easily identify the updates in case of block revert.
Such approach will allow for example to keep track of balance changes and pending FT confirmations (withdrawable balance of a SC will be updated not immediately after a FT is included in a block but after some confirmation block. As an extreme example it will not be possible to have a certificate using the balance increased by a FT within the same block).

2019-09-27 16:08 UTC, albertog78 commented on src/miner.cpp
> +            // nTotalIn = tx.GetValueOut() - nFee;
?

2019-09-27 16:08 UTC, albertog78 commented on src/miner.cpp
> +            if ( !Sidechain::ScMgr::instance().checkSidechainForwardTransaction(tx, state) )
checkSidechainOutputs

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/block.cpp
> +uint256 CBlock::BuildMerkleRootHash(const std::vector<uint256>& vInput, bool* fMutated)
reuse the above method making vtx parametric

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.cpp
> +CAmount CTransaction::GetValueScCreationCcOut() const
sc creation does not have amount in output. remove this

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.cpp
>      return nValueOut;
GetValueOut seems need to return the whole sum of txs outputs including cross chain outputs. This will also prevent to calculate the sum in all the other parts of the code where the value out is needed

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.cpp
> +    if (nVersion != SC_TX_VERSION)
introduce a method to test if tx is SC related to avoid testing version in many places

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +            uint256 ccoutHash = txccout.GetHash();
Separate the logic of cc transfer serialization from the hash calculation for SC map purpose, avoid double hashing and add to the hash the type of cct (eg. 0=FT, 1=CL, ...)

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +class CTxBackwardTransferCrosschainOut : public CTxOut
remove for now

2019-09-27 16:08 UTC, albertog78 commented on src/primitives/transaction.h
> +class CScCertificate
remove for now

2019-09-27 16:08 UTC, albertog78 commented on src/rpc/blockchain.cpp
> +    if (mapBlockIndex.count(blockHash) == 0)
this should never happen unless it's a bug. assert it

2019-09-27 16:08 UTC, albertog78 commented on src/rpc/client.cpp
> +    { "sc_bwdtr", 1},
remove

2019-09-27 16:08 UTC, albertog78 commented on src/rpc/client.cpp
> +    { "sc_fwdtr_many", 0},
sc_sendmany

2019-09-27 16:08 UTC, albertog78 commented on src/rpc/rawtransaction.cpp
> +            if (!Sidechain::ScMgr::instance().fillRawCreation(sc_crs, rawTx, mempool, errString) )
Why mempool is specified? Here we just have to parse the input and fill the tx.
Move out from Sidechain Manager rpc parsing logic

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +    static ScMgr test;
?

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::checkSidechainCreationFunds(const CTransaction& tx, int nHeight)
remove

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::checkSidechainCreation(const CTransaction& tx, CValidationState& state)
to be consistent with existing CheckTransaction approach, implement this method to verify just formal checks and introduce a new instance method to perform checks against the state

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +    if (tx.vsc_ccout.size() )
not needed

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +            if (getScInfo(sc.scId, info) )
remove logic validating the outputs against the state and move such checks in a separate instance method (eg. isValid) that can be called directly for example in accepttomempool, checkblock and wherever coins consistency check is already performed

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::isCreating(const CTransaction& tx, const uint256& scId)
hasSidechainCreationOutput

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::checkSidechainForwardTransaction(const CTransaction& tx, CValidationState& state)
split method as described for siedchainCreation check

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +    if (tx.vft_ccout.size() )
not needed

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::onBlockDisconnected(const CBlock& block, int nHeight)
this should be rewritten considering the CBlockUndo and CTxUndo logic

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +int ScMgr::evalAddCreationFeeOut(CMutableTransaction& tx)
remove this

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +bool ScMgr::fillRawCreation(UniValue& sc_crs, CMutableTransaction& rawTx, CTxMemPool& mempool, std::string& error)
move to sc rpc specific cpp and rename to addSidechainCreationOutputs
remove mempool checks

2019-09-27 16:08 UTC, albertog78 commented on src/sc/sidechain.cpp
> +    evalAddCreationFeeOut(rawTx);
remove this

2019-09-27 16:08 UTC, albertog78 commented on src/wallet/wallet.cpp
> +                CValidationState state;
is this needed here?

2019-09-27 16:08 UTC, albertog78 commented on src/wallet/wallet.cpp
> +
remove if/else

2019-09-27 16:08 UTC, albertog78 commented on src/wallet/walletdb.cpp
> +            static const bool fVerifyingDB = true;
remove

2019-10-02 14:04 UTC, alsala commented on src/main.cpp
> +		if (tx.nVersion > CTransaction::MAX_OLD_VERSION ||
ok

2019-10-02 16:49 UTC, merged

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechain.cpp
> +            if (info.creationTxHash != txHash )
if sc already exists method should return false even if tx we are validating is the one that already crated the sc (in such case means we are trying to apply the same tx twice!)

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechaincore.h
>      bool checkTransaction(const CTransaction& tx, CValidationState& state);
rename to checkTxSemanticValidity as this method perform only semnatic verifications on sc related outputs and make it static because it does not has to have access to sc state

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechaincore.h
> +    bool checkSidechainState(const CTransaction& tx);
rename to isTxApplicableToState

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechaincore.h
> +    bool checkSidechainOutputs(const CTransaction& tx, CValidationState& state);
this seems to be useful only in isTxApplicableToState

2019-10-16 10:24 UTC, albertog78 commented on src/miner.cpp
> +            if ( !Sidechain::ScMgr::instance().checkSidechainOutputs(tx, state) )
call isTxApplicableToState that will check also if tx is trying to recreate an existing sc

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechaincore.h
> +    static void fundCcRecipients(const CTransaction& tx, std::vector<CcRecipientVariant>& vecCcSend);
this seems to belongs to rpc / wallet and not to state. Move out from Sidechain manager

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechain.cpp
>  bool ScMgr::sidechainExists(const uint256& scId)
verify locks in all methods accessing mScInfo map

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechain.cpp
>  void ScMgr::fillJSON(UniValue& result)
move all the json serialization logic out from Sidechain manager and introduce in Sidechain manager a method to retrieve all sc Ids

2019-10-16 10:24 UTC, albertog78 commented on src/sc/sidechaincore.h
> +    void fillJSON(UniValue& result);
move out from SC Manager and rename to AddScInfoToJSON