Sc tx mining dependencies
HorizenOfficial/zen pull request #240
Opened 2020-04-06 07:31 UTC by alsala

Handling of dependency of sc creation and fw transfers txes in mining

2020-04-22 07:37 UTC, abi87 requested changes

2020-04-22 07:37 UTC, abi87 commented on src/miner.cpp
> +        // a certificate has no dependancies, the creation of the sidechain it refers to has happened
The comment is true, however the `view` below does not encompass the mempool. Check CreateNewBlock function defines the view as CCoinsViewCache view(pcoinsTip).
If you want to check (or asserts) that sc creation is not in mempool, lookup for `cert.scId` in `mempool.mapTx` or, prolly faster, check that `mempool.mapSidechains.at(cert.scId).scCreationTxHash.IsNull()`

2020-04-22 07:37 UTC, abi87 commented on src/miner.cpp
>          double dPriority = it_cert->second.GetPriority(nHeight);
I believe `GetPriority` is amenable to be refactored to avoid polymorphism. In other words, `CCoinsViewCache::GetPriority` could accept a CTransactionBase as input and if it is a certificate the max priority can be assigned to it

2020-04-22 07:37 UTC, abi87 commented on src/miner.cpp
>          uint256 hash = tx.GetHash();
hash could be redefined as const reference. Also mempool.ApplyDeltas(...) and mempool.ClearPrioritisation(...) could accept as inputs passed by const ref instead of by value

2020-04-22 07:37 UTC, abi87 commented on src/miner.cpp
> +            assert(mempool.exists(scCreationHash));
Here you should safely assume that mempool internal data structure are well built and coherent and that they can be used without extra checks.
Probably the asserts can be removed at some point.
On the other hand I wonder if you should protect with a lock the access to mempool.mapSidechains

2020-04-22 07:37 UTC, abi87 commented on src/miner.cpp
>              }
Here we are explicitly handling the case of a zero-confirmation spending of a certificate in mempool.
I wonder what happen in light of the coming introduction of maturity for certificate spending.
I would remove this handling altogether as it won't happen and I do not think this is the right place to check mempool coherence.
Prolly merging with cert maturity branch won't be a simple automatic merge

2020-04-22 07:37 UTC, abi87 commented on src/miner.cpp
> +    }
I am not sure we should check coherence of dependency of transactions and certificate in mempool/mainchain.
Why don't we limit ourselves to handle them and leave coherence check to mempool.check?

2020-04-23 09:22 UTC, alsala commented on src/miner.cpp
>          uint256 hash = tx.GetHash();
Ok

2020-04-23 09:24 UTC, alsala commented on src/miner.cpp
> +        // a certificate has no dependancies, the creation of the sidechain it refers to has happened
Ok, added

2020-04-23 09:24 UTC, alsala commented on src/miner.cpp
>          double dPriority = it_cert->second.GetPriority(nHeight);
It makes sense, but it would imply making virtual another method called by it, therefore for the time being I would not do it.

2020-04-23 09:25 UTC, alsala commented on src/miner.cpp
> +            assert(mempool.exists(scCreationHash));
The lock is taken by the caller, but I agree it is useful to add a check that the lock is already taken when excuting that code

2020-04-23 09:44 UTC, alsala commented on src/miner.cpp
>              }
I agree this will be reviewed after the merge with code related to cert maturity

2020-04-23 09:45 UTC, alsala commented on src/miner.cpp
> +    }
This should mimic the behaviour of legacy code

2020-04-23 12:38 UTC, merged