Sc msg cert removal
HorizenOfficial/zen pull request #245
Opened 2020-04-28 09:14 UTC by alsala

Removed MSG_CERT which was added to network protocol for handling certificates and made MSG_TX message able to handle both transactions and certificates.

2020-04-28 15:52 UTC, abi87 requested changes

2020-04-28 15:52 UTC, abi87 commented on src/primitives/transaction.h
> +    virtual bool IsCertificateVersion() const { return false; }
The method `IsCertificateVersion` is never called on a CTransaction. For ScCertificate it is called only once, in `Sidechain::checkCertSemanticValidity(const CScCertificate& cert, CValidationState& state)`
I would remove this method altogether and explicitly compare the versions in 'Sidechain::checkCertSemanticValidity(const CScCertificate& cert, CValidationState& state)'

2020-04-28 15:52 UTC, abi87 commented on src/primitives/transaction.h
> +    virtual bool IsScVersion() const { return false; }
`IsScVersion` is called only on CTransaction, never on CTransactionBase.
I would Remove it for CTransactionBase. Maybe also rename to IsScRelated

2020-04-29 07:41 UTC, alsala commented on src/primitives/transaction.h
> +    virtual bool IsCertificateVersion() const { return false; }
Ok

2020-04-29 07:42 UTC, alsala commented on src/primitives/transaction.h
> +    virtual bool IsScVersion() const { return false; }
Ok, but for now I leave the name as it is

2020-04-29 07:42 UTC, merged