Sc cert vin
HorizenOfficial/zen pull request #246
Opened 2020-05-04 08:00 UTC by alsala

Added vector of inputs to certificate object in order to be able to have a fee charged to the sender of the certificate

2020-05-11 08:19 UTC, abi87 requested changes

2020-05-11 08:19 UTC, abi87 commented on src/txmempool.cpp
> +                }
We currently do not allow zero-conf spending of certificate outputs, neither bwt .
nor changes.
While I would leave in the code for recursive removal of txs or certs zero-conf spending the cert output, I would enforce the impossibility of this spending in the check.
Hence here I would assert that vin is not a certificate in mempool.
Same for transaction inputs above

2020-05-11 08:19 UTC, abi87 commented on src/txmempool.cpp
> +                }
You can probably avoid the duplication as follows
`    // Remove transaction from memory pool
    {
        LOCK(cs);
        std::deque<uint256> objToRemove;
        objToRemove.push_back(origTx.GetHash());

        if(!fRecursive)
            return removeInternal(objToRemove, removedTxs, removedCerts, fRecursive, removeDependantFwds);

        if (!mapCertificate.count(origTx.GetHash()) && !mapTx.count(origTx.GetHash())) {
            // If recursively removing but origTx isn't in the mempool
            // be sure to remove any children that are in the pool. This can
            // happen during chain re-orgs if origCert isn't re-accepted into
            // the mempool for any reason.
            for (unsigned int i = 0; i < origTx.GetVout().size(); i++) {
                std::map<COutPoint, CInPoint>::iterator it = mapNextTx.find(COutPoint(origTx.GetHash(), i));
                if (it == mapNextTx.end())
                    continue;
                LogPrint("sc", "%s():%d - adding tx [%s] to list for removing\n", __func__, __LINE__, it->second.ptx->GetHash().ToString());
                objToRemove.push_back(it->second.ptx->GetHash());
            }

            for(const auto& sc: origTx.GetVscCcOut()) {
                if (mapSidechains.count(sc.scId) == 0)
                    continue;

                if (removeDependantFwds) {
                    for(const auto& fwdTxHash : mapSidechains.at(sc.scId).fwdTransfersSet)
                        objToRemove.push_back(fwdTxHash);
                } else
                    objToRemove.push_back(mapSidechains.at(sc.scId).scCreationTxHash);
            }
        }

        removeInternal(objToRemove, removedTxs, removedCerts, fRecursive, removeDependantFwds);
    }`

2020-05-11 08:19 UTC, abi87 commented on src/txmempool.cpp
>          assert(cert.ContextualCheckInputs(state, mempoolDuplicate, false, chainActive, 0, false, Params().GetConsensus(), NULL));
this polymorphic check is hollow, i.e. it return true for certificates and ::ContextualCheckInputs on txs.
You should remove it and change it for ::ContextualCheckInputs since currently it accepts a CTransactionBase object

2020-05-11 08:19 UTC, abi87 commented on src/txmempool.cpp
> +bool CTxMemPool::addToListForRemovalImmatureExpenditures(
I would inline this

2020-05-11 08:19 UTC, abi87 commented on src/txmempool.cpp
>                  }
I comment here from previous block. Given polymorphism of scOut and fwdOut, you could avoid duplication of the `if(fRecursive)` block which refresh the list of objects to remove and keep different removal of current object, as it is now

2020-05-11 08:19 UTC, abi87 commented on src/txmempool.h
> +    std::shared_ptr<const CTransactionBase> ptx;
I believe a nake pointer should be equally fine here

2020-05-11 08:19 UTC, abi87 commented on src/main.cpp
> +            if (pool.existsCert(vin.prevout.hash)) {
existsCert acquire the mempool lock, which here is not necessary. You can peek into the mapCertificate directly. Same comment for same check in AcceptTxToMemoryPool

2020-05-11 08:19 UTC, abi87 commented on src/wallet/wallet.cpp
> +            return COutputEntry::maturityState::IMMATURE;
You can put all together writing:
```
if (nDepth == 0)
   return COutputEntry::maturityState::IMMATURE;
```

2020-05-11 08:19 UTC, abi87 commented on src/script/interpreter.cpp
> +        }
This serialization facility seems to be used only for hash calculation. I do not see why we need to go back to vbt vs vout vectors. Can't we serialize a single vout, including the isFromBackwardTransfer flag?

2020-05-12 14:24 UTC, alsala commented on src/txmempool.cpp
> +                }
Ok, you are right

2020-05-12 14:24 UTC, alsala commented on src/txmempool.cpp
> +                }
Ok

2020-05-12 14:24 UTC, alsala commented on src/txmempool.cpp
>          assert(cert.ContextualCheckInputs(state, mempoolDuplicate, false, chainActive, 0, false, Params().GetConsensus(), NULL));
Ok

2020-05-12 14:24 UTC, alsala commented on src/txmempool.cpp
> +bool CTxMemPool::addToListForRemovalImmatureExpenditures(
Ok

2020-05-12 14:25 UTC, alsala commented on src/txmempool.cpp
>                  }
Here probably is not that clean as the block above, I am leaving the code as it is

2020-05-12 14:25 UTC, alsala commented on src/txmempool.h
> +    std::shared_ptr<const CTransactionBase> ptx;
Ok, you are right, it is useless here

2020-05-12 14:26 UTC, alsala commented on src/script/interpreter.cpp
> +        }
The serialization is used for the signature, that must be applied on the serialized obj

2020-05-12 14:36 UTC, alsala commented on src/main.cpp
> +            if (pool.existsCert(vin.prevout.hash)) {
Ok

2020-05-13 06:59 UTC, merged