remove getadjusttime, use gettime
HorizenOfficial/zen pull request #250
Opened 2020-05-11 15:20 UTC by ark2038

2020-05-12 19:47 UTC, albertog78 requested changes

2020-05-12 19:47 UTC, albertog78 commented on src/rpc/net.cpp
> +        obj.push_back(Pair("timeoffset", 0));
revert this, timeoffset should be 0 in getnetworkinfo

2020-05-12 19:47 UTC, albertog78 commented on src/rpc/net.cpp
> +            "    \"timeoffset\": ttt,         (numeric) The time offset in seconds (deprecated; always 0)\n"
getnetworkinfo timeoffset is deprecated not this one

2020-05-13 13:25 UTC, cronicc approved these changes

2020-05-13 17:49 UTC, albertog78 approved these changes

2020-05-13 19:37 UTC, merged