Sc proof verifier
HorizenOfficial/zen pull request #294
Opened 2020-06-09 08:49 UTC by DanieleDiBenedetto

2020-06-09 09:06 UTC, albertog78 requested changes

2020-06-09 09:06 UTC, albertog78 commented on depends/packages/crate_ginger_zendoo.mk
> +$(package)_download_path=https://github.com/ark2038/ginger-lib/archive/
why not the official one?

2020-06-09 09:06 UTC, albertog78 commented on depends/packages/crate_r1cs_core_zendoo.mk
> +$(package)_download_path=https://github.com/ark2038/r1cs-core/archive/
why not the official one?

2020-06-09 09:06 UTC, albertog78 commented on depends/packages/librustzcash.mk
> +$(package)_download_path=https://github.com/ark2038/librustzcash/archive/
use the official one and then apply a patch

2020-06-10 10:34 UTC, albertog78 approved these changes

2020-06-10 11:13 UTC, i-Alex approved these changes

2020-06-10 11:14 UTC, merged