Mo/getblock verbose
HorizenOfficial/zen pull request #325
Opened 2020-10-01 12:56 UTC by MarcoOl94

2020-10-01 13:22 UTC, alsala approved these changes

2020-10-07 09:46 UTC, abi87 requested changes

2020-10-07 09:46 UTC, abi87 commented on src/rpc/blockchain.cpp
> +             "2. verbosity              (numeric, optional, default=1) 0 for hex encoded data, 1 for a json object, and 2 for json object with transaction data\n"
While here verbosity is reported as numeric, later on you handle the case it is boolean, for backward compatibility I guess. Should we extend the help reporting that older boolean True is mapped to verbosity=1 and False to 0?

2020-10-09 13:26 UTC, albertog78 approved these changes

2020-10-13 10:40 UTC, merged