Review  and fix RPC call messages
HorizenOfficial/zen pull request #369
Opened 2021-03-08 01:42 UTC by luisantoniocrag

fix #328 
WIP

2021-05-01 18:37 UTC, sonzap006 reviewed
n

2021-05-01 18:37 UTC, sonzap006 reviewed
Good

2021-05-10 08:44 UTC, cronicc requested changes

2021-05-10 08:44 UTC, cronicc commented on src/rpc/blockchain.cpp
> +            "\nReturns the hash of the best (most recent) block in the longest block chain.\n"
```suggestion
            "\nReturns the hash of the best (most recent) block in the active block chain.\n"
```
Best to word it like this, as with our penalty system for delayed block submission it's possible that the longest chain is not the active/best chain.

2021-05-10 08:44 UTC, cronicc commented on src/rpc/blockchain.cpp
> +            "  ...,                                 same output as verbosity = 2\n"
```suggestion
            "  ...,                                 same output as verbosity = 1\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/blockchain.cpp
> +            + HelpExampleRpc("getglobaltips", "\"hash\"")
```suggestion
            + HelpExampleCli("getglobaltips", "")
            + HelpExampleRpc("getglobaltips", "")
```
Takes no arguments.

2021-05-10 08:44 UTC, cronicc commented on src/rpc/blockchain.cpp
> +            "n         (numeric) number of consecutive blocks a miner should mine from now in order to revert the block of given hash\n"
```suggestion
            "\nReturns the minimum number of consecutive blocks a miner would have to mine from now in order to revert the block of given hash\n"

            "\nArguments:\n"
            "1. hash   (string, required)  the block hash"

            "\"Result:\n"
            "n         (numeric) number of consecutive blocks a miner would have to mine from now in order to revert the block of given hash\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/mining.cpp
> +            "  \"supernodes\": xxxx       (numeric) the supernodes fund amount in " + CURRENCY_UNIT + " (only if supernode HF fund is available)\n"
```suggestion
            "  \"securenodes\": xxxx,     (numeric) the securenodes fund amount in " + CURRENCY_UNIT + "\n"
            "  \"supernodes\": xxxx       (numeric) the supernodes fund amount in " + CURRENCY_UNIT + "\n"
```
As the fork is active now this can be removed.

2021-05-10 08:44 UTC, cronicc commented on src/rpc/misc.cpp
> +            "\nVerify an ZEN address is valid.\n"
```suggestion
            "\nReturn information about the given ZEN address.\n"
```
Original wording was OK.

2021-05-10 08:44 UTC, cronicc commented on src/rpc/misc.cpp
> +            "\nVerify an zaddress is valid.\n"
```suggestion
            "\nReturn information about the given zaddress.\n"
```
Original wording was OK.

2021-05-10 08:44 UTC, cronicc commented on src/rpc/misc.cpp
> +            "               pass 0 to go back to using the system tim."
```suggestion
            "               pass 0 to go back to using the system time."
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/net.cpp
> +            "    \"tls_verified\": true|false,           (boolean) status of peer certificate. Will be true if a peer certificate can be verified with some trusted root certs \n"
```suggestion
            "    \"tls_verified\": true|false,           (boolean) status of peer certificate. True if the chain of trust of a peer certificate can be verified using the OS certificate store\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/net.cpp
>              + HelpExampleRpc("disconnectnode", "\"192.168.0.6:8233\"")
```suggestion
            + HelpExampleCli("disconnectnode", "\"192.168.0.6:9033\"")
            + HelpExampleRpc("disconnectnode", "\"192.168.0.6:9033\"")
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/net.cpp
> +            "  \"networks\": [                                (array) an array of objects describing IPV4, IPV6 and Onion network interface states\n"
```suggestion
            "  \"networks\": [                                (array) an array of objects describing IPV4, IPV6 and Onion network status\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/net.cpp
> +            "2. \"command\"      (string, required) 'add' to add a IP/Subnet to the list, 'remove' to remove a IP/Subnet from the list\n"
```suggestion
            "\nAttempts to add or remove an IP/Subnet from the banned list.\n"
            
            "\nArguments:\n"
            "1. \"ip(/netmask)\" (string, required) the IP/Subnet (see getpeerinfo for nodes ip) with an optional netmask (default is /32 = single ip)\n"
            "2. \"command\"      (string, required) 'add' to add an IP/Subnet to the list, 'remove' to remove an IP/Subnet from the list\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/rawtransaction.cpp
> +            "       \"vout\": n,                  (numeric) the output number\n"
```suggestion
            "       \"vout\": n,                  (numeric) the output index\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/rawtransaction.cpp
> +            "  \"vjoinsplit\" : [                 (array of json objects, only for version >= 2)\n"
```suggestion
            "  \"vjoinsplit\" : [                 (array of json objects, only for version 2 or -3)\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/rawtransaction.cpp
> +            "       \"vout\": n,                                  (numeric) the output number\n"
```suggestion
            "       \"vout\": n,                                  (numeric) the output index\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/rawtransaction.cpp
> +            "  \"vjoinsplit\": [                                  (array of json objects, only for version >= 2)\n"
```suggestion
            "  \"vjoinsplit\": [                                  (array of json objects, only for version 2 or -3)\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/rpc/rawtransaction.cpp
> +            "2. \"prevtxs\"                        (string, optional) an json array of previous dependent transaction outputs\n"
```suggestion
            "2. \"prevtxs\"                        (string, optional) a json array of previous dependent transaction outputs\n"
```

2021-05-10 08:44 UTC, cronicc commented on src/wallet/rpcdump.cpp
> +            + HelpExampleCli("z_importkey", "\"zaddr\"")
```suggestion
            + HelpExampleCli("z_importkey", "\"zkey\"")
```

2021-05-10 08:44 UTC, cronicc commented on src/wallet/rpcwallet.cpp
>              + HelpExampleRpc("setaccount", "\"t14oHp2v54vfmdgQ3v3SNuQga8JKHTNi2a1\", \"tabby\"")
```suggestion
            + HelpExampleCli("setaccount", "\"horizenaddress\" \"tabby\"")
            + HelpExampleRpc("setaccount", "\"horizenaddress\", \"tabby\"")
```

2021-05-10 08:50 UTC, cronicc commented
Hi @luisantoniocrag 

Thanks for doing this, I know how much work it involves. I've left a couple of change requests.

Please also change the RPC ports to 8231/18231 where we missed changing them originally.

https://github.com/luisantoniocrag/zen/blob/d41a781c7ded21c07a1e32919cba0d90fcc99da6/src/rpc/server.cpp#L613
https://github.com/luisantoniocrag/zen/blob/d41a781c7ded21c07a1e32919cba0d90fcc99da6/src/init.cpp#L554

2021-05-11 12:31 UTC, luisantoniocrag commented
Thanks for reviewing @cronicc. I committed the suggested changes and update the rpc ports.

2021-05-14 14:03 UTC, cronicc requested changes
@luisantoniocrag 
Hi, I've found two more small changes to make.

Once these are addressed, please rebase (squash) all of the commits from the change requests down to a single commit.

Here is a useful tutorial on squashing http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2021-05-14 14:03 UTC, cronicc commented on src/rpc/blockchain.cpp
> +            "\"Result:\n"
```suggestion
            "1. hash   (string, required)  the block hash\n"

            "\nResult:\n"
```

2021-05-14 14:03 UTC, cronicc commented on src/rpc/net.cpp
>              "\nbResult:\n"
```suggestion
            "\nResult:\n"
```

2021-05-14 15:08 UTC, luisantoniocrag commented
@cronicc 
squashed 
https://github.com/HorizenOfficial/zen/pull/369/commits/cffe8ec17ba94d00ede271228055bf2bc1bead33

2021-05-14 15:53 UTC, cronicc approved these changes

2021-05-14 15:57 UTC, cronicc commented
@luisantoniocrag Approved, thanks for the contribution!

I've changed the base branch of the PR as this will need additional review from a second developer before our next release window and everyone is busy working on zend_oo at the moment.

But it will eventually end up in development and master :)

2021-05-14 15:58 UTC, merged