Improvements of the build system
HorizenOfficial/zen pull request #431
Opened 2022-01-14 18:18 UTC by ptagl

- Added a new `configure` argument to enable the `-Wall` flag during the compilation
- Added the `--use-clang` argument to `build.sh` to switch the compilation from `gcc` to `clang`
- Added some scripts to perform static code analysis with `cppcheck` and `oclint`

2022-01-14 18:21 UTC, ptagl commented
Additional improvements that might be implemented:

- Add a readme to provide instructions about the usage of Clang static analysis tools (e.g. `scan-build`)
- Check that the full build output (from a perfectly clean cloned repository) for any architecture (Linux, Windows cross compiled, Mac OS) is perfectly identical to the output from the `development` branch when not using Clang

2022-06-20 10:27 UTC, drgora commented on doc/static-code-analysis.md
> +By default Zen is compiled with GCC, but it's easy to switch to Clang by calling `zcutil/build.sh` with the flag `--use-clang`. Using Clang together with `wall` or `werror` tipically generates a diff
I'd suggest to make it clear that this is true only for Linux.

2022-06-20 13:17 UTC, a-petrini requested changes

2022-06-20 13:17 UTC, a-petrini commented on zcutil/build.sh
> +if [ "x${1:-}" = 'x--use-clang' ]; then
As we introduced the new `--use-clang` option to build.sh, I suggest to add a short description to the message returned by the `--help` option on the same file.

2022-06-20 13:17 UTC, a-petrini commented on qa/lint/extended-lint-cppcheck.sh
> +function join_array {
This function was originally used in tandem with grep to filter some specific warnings. As we now rely on an explicit suppression list, this function is unused and should be removed.

2022-06-20 13:17 UTC, a-petrini commented on configure.ac
> +  if test "x$CXXFLAG_WERROR" = "x"; then
We are checking if the compiler supports the `-wall` flag in case we request compilation with all warnings enabled, however we are checking against the wrong var `$CXXFLAG_WERROR`.

2022-06-20 13:41 UTC, ptagl commented on doc/static-code-analysis.md
> +By default Zen is compiled with GCC, but it's easy to switch to Clang by calling `zcutil/build.sh` with the flag `--use-clang`. Using Clang together with `wall` or `werror` tipically generates a diff
Fixed with commit [3d4a66d4b49dcda0db45db5837374851f2f49505](https://github.com/HorizenOfficial/zen/pull/431/commits/3d4a66d4b49dcda0db45db5837374851f2f49505).

2022-06-20 13:42 UTC, ptagl commented on zcutil/build.sh
> +if [ "x${1:-}" = 'x--use-clang' ]; then
Fixed with commit [e51a7f19bb6b03c28a9cc3238ed771ea5f5e9d27](https://github.com/HorizenOfficial/zen/commit/e51a7f19bb6b03c28a9cc3238ed771ea5f5e9d27).

2022-06-20 13:42 UTC, ptagl commented on qa/lint/extended-lint-cppcheck.sh
> +function join_array {
Fixed with commit [01ebdbfb657ffdaa6f154b44a8add9a1b479a452](https://github.com/HorizenOfficial/zen/pull/431/commits/01ebdbfb657ffdaa6f154b44a8add9a1b479a452).

2022-06-20 13:43 UTC, ptagl commented on configure.ac
> +  if test "x$CXXFLAG_WERROR" = "x"; then
Fixed with commit [9ece8da4c399503296e98ec21809b1e09fd8b8cb](https://github.com/HorizenOfficial/zen/commit/9ece8da4c399503296e98ec21809b1e09fd8b8cb).

2022-06-21 10:20 UTC, a-petrini approved these changes

2022-06-21 10:44 UTC, drgora approved these changes

2022-07-13 10:47 UTC, cronicc approved these changes

2022-07-18 09:20 UTC, merged