Prepare management for fork 10
HorizenOfficial/zen pull request #458
Opened 2022-06-29 08:31 UTC by a-petrini

This PR introduces the mandatory changes to the ForkManager class for the upcoming fork #10:
- updates to ForkManager class
- updates to the corresponding test unit
- updates to Python RPC test
In Python tests, height-related global variables have been gathered into a single dictionary.

2022-06-29 08:43 UTC, drgora approved these changes
Looks good to me, thanks

2022-06-29 13:07 UTC, ptagl requested changes

2022-06-29 13:07 UTC, ptagl commented on qa/rpc-tests/sc_cert_addressindex.py
> +from test_framework.test_framework import BitcoinTestFramework, ForkHeights
It seems like `ForkHeights` is imported twice.

2022-06-29 13:07 UTC, ptagl commented on qa/rpc-tests/sc_cert_ceasing_split.py
> +from test_framework.test_framework import ForkHeights
It seems like `ForkHeights` is imported twice.

2022-06-29 13:07 UTC, ptagl commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundReward
The community fund addresses will not be changed in the next release, so I guess we can remove the comment.

2022-06-29 13:07 UTC, ptagl commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundAddress / communityFundAddressMap
The community fund addresses will not be changed in the next release, so I guess we can remove the comment.

2022-06-29 13:07 UTC, ptagl commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundAddress / secureNodeFundAddressMap
The community fund addresses will not be changed in the next release, so I guess we can remove the comment.

2022-06-29 13:07 UTC, ptagl commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundAddress / superNodeFundAddressMap
The community fund addresses will not be changed in the next release, so I guess we can remove the comment.

2022-06-29 13:07 UTC, ptagl commented on src/gtest/test_forkmanager.cpp
> +///
If I understand correctly the comment, I guess it can be removed as the related tests have already been implemented.

2022-06-29 13:07 UTC, ptagl commented on qa/rpc-tests/sc_version.py
I know it's a little paranoid, but I would like to have an additional "section" here in which we test that in the block immediately before `NON_CEASING_SC` the creation of sidechain v2 is still rejected, also for consistency with other tests developed in the past.

2022-06-29 17:03 UTC, drgora commented on qa/rpc-tests/sc_cert_addressindex.py
> +from test_framework.test_framework import BitcoinTestFramework, ForkHeights
Good catch, thanks! Fixed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:03 UTC, drgora commented on qa/rpc-tests/sc_cert_ceasing_split.py
> +from test_framework.test_framework import ForkHeights
Fixed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:03 UTC, drgora commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundReward
Removed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:03 UTC, drgora commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundAddress / communityFundAddressMap
Removed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:03 UTC, drgora commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundAddress / secureNodeFundAddressMap
Removed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:03 UTC, drgora commented on src/gtest/test_forkmanager.cpp
> +/// AP - to do: add a test if changes in CommunityFundAddress / superNodeFundAddressMap
Removed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:04 UTC, drgora commented on src/gtest/test_forkmanager.cpp
> +///
Removed with f29ced54bf2ec0114d5daf1b2c5636e36421930c

2022-06-29 17:04 UTC, drgora commented on qa/rpc-tests/sc_version.py
Makes sense, f29ced54bf2ec0114d5daf1b2c5636e36421930c updates the test to include this additional check, thanks

2022-07-01 07:58 UTC, ptagl approved these changes

2022-07-13 11:20 UTC, cronicc approved these changes

2022-07-19 04:59 UTC, merged