Gp/support indexing for p2 pk
HorizenOfficial/zen pull request #541
Opened 2023-04-21 09:11 UTC by JackPiri

This PR adds support for Pay-To-Public-Key (P2PK) scripts; before this PR only Pay-To-Public-Key-Hash (P2PKH) and Pay-To-Script-Hash (P2SH) scripts were supported.
Pull request associated to issue [#352](https://github.com/HorizenOfficial/zen/issues/352).
Notice: this is a rebased clone of PR [#480](https://github.com/HorizenOfficial/zen/pull/480).

2023-04-28 07:45 UTC, drgora approved these changes
Looks good to me

2023-05-02 10:31 UTC, a-petrini requested changes

2023-05-02 10:31 UTC, a-petrini commented on src/main.h
> +#ifdef ENABLE_ADDRESS_INDEXING
This define has been removed from the codebase with PR https://github.com/HorizenOfficial/zen/pull/531 so it should not be introduced back.

2023-05-02 10:31 UTC, a-petrini commented on src/rpc/blockchain.cpp
> +#ifdef ENABLE_ADDRESS_INDEXING
As in `main.h`, this define has been removed from the codebase with PR https://github.com/HorizenOfficial/zen/pull/531 so it should not be introduced back.

2023-05-02 10:31 UTC, a-petrini commented on src/rpc/misc.cpp
> +#ifdef ENABLE_ADDRESS_INDEXING
As in `main.h`, this define has been removed from the codebase with PR https://github.com/HorizenOfficial/zen/pull/531 so it should not be introduced back.

2023-05-02 12:26 UTC, JackPiri commented on src/rpc/blockchain.cpp
> +#ifdef ENABLE_ADDRESS_INDEXING
Yes, this is a wrong rebasing; modified accordingly.

2023-05-02 12:26 UTC, JackPiri commented on src/main.h
> +#ifdef ENABLE_ADDRESS_INDEXING
Yes, this is a wrong rebasing; modified accordingly.

2023-05-02 12:26 UTC, JackPiri commented on src/rpc/misc.cpp
> +#ifdef ENABLE_ADDRESS_INDEXING
Yes, this is a wrong rebasing; modified accordingly.

2023-05-02 13:59 UTC, a-petrini commented on src/main.h
> +#ifdef ENABLE_ADDRESS_INDEXING
Nice, thanks!

2023-05-02 14:00 UTC, a-petrini approved these changes

2023-05-09 11:45 UTC, ptagl approved these changes

2023-05-10 11:03 UTC, merged