Gp/release management scripts
HorizenOfficial/zen pull request #551
Opened 2023-05-15 12:47 UTC by JackPiri

This PR targets:

- release preparation script
  - added configurability (skip/stop) for initialization "check main checked out" and "check no pending changes" steps, in order to allow more flexibility in case of non-standard usage of script
  - added step for checking for dependencies availability
  - remove `authors.md` file update (removal of file itself)
  - added update of `CLIENT_VERSION_IS_RELEASE` macro
 
- release backport script
  - added script for release backporting (from the docs: _"A successful run of the script would create a new branch starting from currently selected commit of `main` branch (a different branch can be configured) and would perform one single commit containing all the release backport steps."_)

2023-05-17 12:47 UTC, a-petrini approved these changes
PR looks fine! Left a few non blocking suggestions

2023-05-17 12:47 UTC, a-petrini commented on doc/release-process.md
> +	  and "total_transactions" are set based
Is this line incomplete?

2023-05-17 12:47 UTC, a-petrini commented on doc/release-process.md
> +- create annotated tag (vX.Y.Z)
I would add that tag creation and push should be performed after the release preparation branch has been merged into the release branch

2023-05-17 12:47 UTC, a-petrini commented on contrib/devtools/release_management/release_preparation.py
> +        # config_file = "config.yaml"
Can we remove this comment?

2023-05-17 13:58 UTC, JackPiri commented on doc/release-process.md
> +	  and "total_transactions" are set based
You are right, _and "total_transactions" are set based_ is a leftover; took the chance also for fixing indentation.

2023-05-17 14:01 UTC, JackPiri commented on contrib/devtools/release_management/release_preparation.py
> +        # config_file = "config.yaml"
For sure, removed comment from both `release_preparation.py` and `release_backport.py`.

2023-05-17 14:01 UTC, JackPiri commented on doc/release-process.md
> +- create annotated tag (vX.Y.Z)
Ok makes sense, modified as per your suggestion.

2023-05-17 15:26 UTC, drgora approved these changes
Looks good to me, thanks

2023-05-17 15:29 UTC, a-petrini commented on contrib/devtools/release_management/release_preparation.py
> +        # config_file = "config.yaml"
Thanks, everything looks fine and I resolve all conversations

2023-05-22 15:57 UTC, ptagl requested changes

2023-05-22 15:57 UTC, ptagl commented on doc/release-process.md
> +- once the release preparation branch is merged into the release branch, create annotated tag (vX.Y.Z)
Just as a reminder, in particular for me as I always forget that detail, can we mention the full command to create the signed annotated tag?

Not sure if this applies also to `contrib/devtools/README.md` as I see some overlapping.

```suggestion
- once the release preparation branch is merged into the release branch, create annotated tag (vX.Y.Z), for example `git tag -s -m"v4.0.0" v4.0.0`
```

2023-05-22 15:57 UTC, ptagl commented on README.md
> +Zend 4.0.99
Even though the main readme file has always included the current release version, it looks weird to me to see it now as X.Y.99 as it is not a real release.

What about getting rid of the version? In case, we would need to update the release script to skip this file.

```suggestion
Zend
```

2023-05-22 16:24 UTC, JackPiri commented on README.md
> +Zend 4.0.99
Ok, updated single file and scripts step accordingly.

2023-05-22 16:34 UTC, JackPiri commented on doc/release-process.md
> +- once the release preparation branch is merged into the release branch, create annotated tag (vX.Y.Z)
I've modified a little bit differently as `git tag -a v4.0.0 -m "v4.0.0"` (please note `-a` instead of `-s`).

2023-05-23 15:35 UTC, JackPiri commented on doc/release-process.md
> +- once the release preparation branch is merged into the release branch, create annotated tag (vX.Y.Z)
Sorry, finally modified with your proposal.

2023-05-23 15:40 UTC, ptagl approved these changes

2023-05-23 15:44 UTC, merged